version: '3.9'

services:
  test-postgres:
    image: postgres:15
    container_name: test-postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - "5444:5432"  
    volumes:
      - test_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser"]
      interval: 5s
      retries: 10
      start_period: 5s

volumes:
  test_pg_data:
