FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src
COPY . .
WORKDIR /src/IncidentReportingSystem.API
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
	
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["sh", "-c", "./wait-for.sh \"$POSTGRES_HOST:$POSTGRES_PORT\" dotnet IncidentReportingSystem.API.dll"]
