//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncidentReportingSystem.UI.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_AppTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_AppTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IncidentReportingSystem.UI.Localization.Localization.AppTexts", typeof(Localization_AppTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized or your session expired. Please sign in again..
        /// </summary>
        internal static string Account_NotAuthorized_Body {
            get {
                return ResourceManager.GetString("Account.NotAuthorized.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        internal static string Account_NotAuthorized_Title {
            get {
                return ResourceManager.GetString("Account.NotAuthorized.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        internal static string Account_Title {
            get {
                return ResourceManager.GetString("Account.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Action_Back {
            get {
                return ResourceManager.GetString("Action.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to sign in.
        /// </summary>
        internal static string Action_GoSignIn {
            get {
                return ResourceManager.GetString("Action.GoSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Action_Logout {
            get {
                return ResourceManager.GetString("Action.Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Action_Register {
            get {
                return ResourceManager.GetString("Action.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Action_SignIn {
            get {
                return ResourceManager.GetString("Action.SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Aria_Loading {
            get {
                return ResourceManager.GetString("Aria.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed.
        /// </summary>
        internal static string Auth_Register_Failed {
            get {
                return ResourceManager.GetString("Auth.Register.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string Auth_Register_Title {
            get {
                return ResourceManager.GetString("Auth.Register.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in failed.
        /// </summary>
        internal static string Auth_SignIn_Failed {
            get {
                return ResourceManager.GetString("Auth.SignIn.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string Auth_SignIn_Title {
            get {
                return ResourceManager.GetString("Auth.SignIn.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Reporting.
        /// </summary>
        internal static string Brand_Title {
            get {
                return ResourceManager.GetString("Brand.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string Btn_Create {
            get {
                return ResourceManager.GetString("Btn.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Btn_SignIn {
            get {
                return ResourceManager.GetString("Btn.SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        internal static string Error_Login {
            get {
                return ResourceManager.GetString("Error.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed..
        /// </summary>
        internal static string Error_Register {
            get {
                return ResourceManager.GetString("Error.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Field_Email {
            get {
                return ResourceManager.GetString("Field.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string Field_FirstName {
            get {
                return ResourceManager.GetString("Field.FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string Field_LastName {
            get {
                return ResourceManager.GetString("Field.LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string Field_Name {
            get {
                return ResourceManager.GetString("Field.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Field_Password {
            get {
                return ResourceManager.GetString("Field.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Field_Role {
            get {
                return ResourceManager.GetString("Field.Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Field_Roles {
            get {
                return ResourceManager.GetString("Field.Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By continuing you agree to the Terms..
        /// </summary>
        internal static string Legal_Continue {
            get {
                return ResourceManager.GetString("Legal.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Account.
        /// </summary>
        internal static string Nav_Account {
            get {
                return ResourceManager.GetString("Nav.Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Option_Admin {
            get {
                return ResourceManager.GetString("Option.Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string Option_User {
            get {
                return ResourceManager.GetString("Option.User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Role_Admin {
            get {
                return ResourceManager.GetString("Role.Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a role….
        /// </summary>
        internal static string Role_SelectPlaceholder {
            get {
                return ResourceManager.GetString("Role.SelectPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string Role_User {
            get {
                return ResourceManager.GetString("Role.User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are signed in..
        /// </summary>
        internal static string SignedIn_Message {
            get {
                return ResourceManager.GetString("SignedIn.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Tab_Login {
            get {
                return ResourceManager.GetString("Tab.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string Tab_Register {
            get {
                return ResourceManager.GetString("Tab.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast and simple workflow.
        /// </summary>
        internal static string Welcome_Point_Fast {
            get {
                return ResourceManager.GetString("Welcome.Point.Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern, responsive UI.
        /// </summary>
        internal static string Welcome_Point_Modern {
            get {
                return ResourceManager.GetString("Welcome.Point.Modern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure authentication &amp; roles.
        /// </summary>
        internal static string Welcome_Point_Secure {
            get {
                return ResourceManager.GetString("Welcome.Point.Secure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in or create an account to continue..
        /// </summary>
        internal static string Welcome_Subtitle {
            get {
                return ResourceManager.GetString("Welcome.Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build incidents faster. Safely..
        /// </summary>
        internal static string Welcome_Title {
            get {
                return ResourceManager.GetString("Welcome.Title", resourceCulture);
            }
        }
    }
}
