//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncidentReportingSystem.UI.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_AppTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_AppTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IncidentReportingSystem.UI.Localization.Localization.AppTexts", typeof(Localization_AppTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string Account_Action_ChangePassword {
            get {
                return ResourceManager.GetString("Account.Action.ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        internal static string Account_ChangePassword_Success {
            get {
                return ResourceManager.GetString("Account.ChangePassword.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string Account_ChangePassword_Title {
            get {
                return ResourceManager.GetString("Account.ChangePassword.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update profile.
        /// </summary>
        internal static string Account_Edit_Failed {
            get {
                return ResourceManager.GetString("Account.Edit.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated.
        /// </summary>
        internal static string Account_Edit_Success {
            get {
                return ResourceManager.GetString("Account.Edit.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        internal static string Account_Edit_Title {
            get {
                return ResourceManager.GetString("Account.Edit.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized or your session expired. Please sign in again..
        /// </summary>
        internal static string Account_NotAuthorized_Body {
            get {
                return ResourceManager.GetString("Account.NotAuthorized.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        internal static string Account_NotAuthorized_Title {
            get {
                return ResourceManager.GetString("Account.NotAuthorized.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        internal static string Account_Title {
            get {
                return ResourceManager.GetString("Account.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Action_Back {
            get {
                return ResourceManager.GetString("Action.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create incident.
        /// </summary>
        internal static string Action_CreateIncident {
            get {
                return ResourceManager.GetString("Action.CreateIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Action_Download {
            get {
                return ResourceManager.GetString("Action.Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to sign in.
        /// </summary>
        internal static string Action_GoSignIn {
            get {
                return ResourceManager.GetString("Action.GoSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Action_Logout {
            get {
                return ResourceManager.GetString("Action.Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Action_Open {
            get {
                return ResourceManager.GetString("Action.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Action_Refresh {
            get {
                return ResourceManager.GetString("Action.Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Action_Register {
            get {
                return ResourceManager.GetString("Action.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Action_Save {
            get {
                return ResourceManager.GetString("Action.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Action_SignIn {
            get {
                return ResourceManager.GetString("Action.SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Aria_Loading {
            get {
                return ResourceManager.GetString("Aria.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Ation_Close {
            get {
                return ResourceManager.GetString("Ation.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Attachments_Add {
            get {
                return ResourceManager.GetString("Attachments.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Attachments_Cancel {
            get {
                return ResourceManager.GetString("Attachments.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Attachments_Download {
            get {
                return ResourceManager.GetString("Attachments.Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a file.
        /// </summary>
        internal static string Attachments_Form_PickFile {
            get {
                return ResourceManager.GetString("Attachments.Form.PickFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed file types.
        /// </summary>
        internal static string Attachments_Hint_Allowed {
            get {
                return ResourceManager.GetString("Attachments.Hint.Allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max size {0} MB.
        /// </summary>
        internal static string Attachments_Hint_MaxSize {
            get {
                return ResourceManager.GetString("Attachments.Hint.MaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to upload.
        /// </summary>
        internal static string Attachments_Hint_SelectFile {
            get {
                return ResourceManager.GetString("Attachments.Hint.SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Attachments_Open {
            get {
                return ResourceManager.GetString("Attachments.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful.
        /// </summary>
        internal static string Auth_Login_Success {
            get {
                return ResourceManager.GetString("Auth.Login.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed.
        /// </summary>
        internal static string Auth_Register_Failed {
            get {
                return ResourceManager.GetString("Auth.Register.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful.
        /// </summary>
        internal static string Auth_Register_Success {
            get {
                return ResourceManager.GetString("Auth.Register.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string Auth_Register_Title {
            get {
                return ResourceManager.GetString("Auth.Register.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in failed.
        /// </summary>
        internal static string Auth_SignIn_Failed {
            get {
                return ResourceManager.GetString("Auth.SignIn.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string Auth_SignIn_Title {
            get {
                return ResourceManager.GetString("Auth.SignIn.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Reporting.
        /// </summary>
        internal static string Brand_Title {
            get {
                return ResourceManager.GetString("Brand.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string Btn_Create {
            get {
                return ResourceManager.GetString("Btn.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Btn_SignIn {
            get {
                return ResourceManager.GetString("Btn.SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment.
        /// </summary>
        internal static string Comments_Add {
            get {
                return ResourceManager.GetString("Comments.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Comments_Cancel {
            get {
                return ResourceManager.GetString("Comments.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comments yet..
        /// </summary>
        internal static string Comments_Empty {
            get {
                return ResourceManager.GetString("Comments.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment cannot be empty..
        /// </summary>
        internal static string Comments_Error_Empty {
            get {
                return ResourceManager.GetString("Comments.Error.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add comment. Please try again..
        /// </summary>
        internal static string Comments_Error_Failed {
            get {
                return ResourceManager.GetString("Comments.Error.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters: {0}/{1}.
        /// </summary>
        internal static string Comments_Form_Counter {
            get {
                return ResourceManager.GetString("Comments.Form.Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your comment here.
        /// </summary>
        internal static string Comments_Form_Placeholder {
            get {
                return ResourceManager.GetString("Comments.Form.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Comments_Form_Submit {
            get {
                return ResourceManager.GetString("Comments.Form.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading comments….
        /// </summary>
        internal static string Comments_Loading {
            get {
                return ResourceManager.GetString("Comments.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a comment….
        /// </summary>
        internal static string Comments_Placeholder {
            get {
                return ResourceManager.GetString("Comments.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Comments_Submit {
            get {
                return ResourceManager.GetString("Comments.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Common_Next {
            get {
                return ResourceManager.GetString("Common.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Common_Page {
            get {
                return ResourceManager.GetString("Common.Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Common_Prev {
            get {
                return ResourceManager.GetString("Common.Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string Common_Reload {
            get {
                return ResourceManager.GetString("Common.Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Common_Total {
            get {
                return ResourceManager.GetString("Common.Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents by category.
        /// </summary>
        internal static string Dashboard_Chart_ByCategory {
            get {
                return ResourceManager.GetString("Dashboard.Chart.ByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents by severity.
        /// </summary>
        internal static string Dashboard_Chart_BySeverity {
            get {
                return ResourceManager.GetString("Dashboard.Chart.BySeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents by status.
        /// </summary>
        internal static string Dashboard_Chart_ByStatus {
            get {
                return ResourceManager.GetString("Dashboard.Chart.ByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string Dashboard_Chart_Series_Count {
            get {
                return ResourceManager.GetString("Dashboard.Chart.Series.Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents over time.
        /// </summary>
        internal static string Dashboard_Chart_Timeseries {
            get {
                return ResourceManager.GetString("Dashboard.Chart.Timeseries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        internal static string Dashboard_Empty {
            get {
                return ResourceManager.GetString("Dashboard.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard could not be loaded.
        /// </summary>
        internal static string Dashboard_Error {
            get {
                return ResourceManager.GetString("Dashboard.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed incidents.
        /// </summary>
        internal static string Dashboard_Kpi_Closed {
            get {
                return ResourceManager.GetString("Dashboard.Kpi.Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open incidents.
        /// </summary>
        internal static string Dashboard_Kpi_Open {
            get {
                return ResourceManager.GetString("Dashboard.Kpi.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total incidents.
        /// </summary>
        internal static string Dashboard_Kpi_Total {
            get {
                return ResourceManager.GetString("Dashboard.Kpi.Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to My Profile.
        /// </summary>
        internal static string Dashboard_Link_Profile {
            get {
                return ResourceManager.GetString("Dashboard.Link.Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Dashboard_Loading {
            get {
                return ResourceManager.GetString("Dashboard.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a minimal dashboard placeholder..
        /// </summary>
        internal static string Dashboard_Mvp_Placeholder {
            get {
                return ResourceManager.GetString("Dashboard.Mvp.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Incidents.
        /// </summary>
        internal static string Dashboard_Total {
            get {
                return ResourceManager.GetString("Dashboard.Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong..
        /// </summary>
        internal static string Error_Generic {
            get {
                return ResourceManager.GetString("Error.Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        internal static string Error_Login {
            get {
                return ResourceManager.GetString("Error.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed..
        /// </summary>
        internal static string Error_Register {
            get {
                return ResourceManager.GetString("Error.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CSV.
        /// </summary>
        internal static string Export_CSV {
            get {
                return ResourceManager.GetString("Export.CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Field_Category {
            get {
                return ResourceManager.GetString("Field.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Field_Description {
            get {
                return ResourceManager.GetString("Field.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Field_Email {
            get {
                return ResourceManager.GetString("Field.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string Field_FirstName {
            get {
                return ResourceManager.GetString("Field.FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string Field_LastName {
            get {
                return ResourceManager.GetString("Field.LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Field_Location {
            get {
                return ResourceManager.GetString("Field.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string Field_Name {
            get {
                return ResourceManager.GetString("Field.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Field_Password {
            get {
                return ResourceManager.GetString("Field.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string Field_Password_Confirm {
            get {
                return ResourceManager.GetString("Field.Password.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string Field_Password_Current {
            get {
                return ResourceManager.GetString("Field.Password.Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string Field_Password_New {
            get {
                return ResourceManager.GetString("Field.Password.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reported at.
        /// </summary>
        internal static string Field_ReportedAt {
            get {
                return ResourceManager.GetString("Field.ReportedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Field_Role {
            get {
                return ResourceManager.GetString("Field.Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Field_Roles {
            get {
                return ResourceManager.GetString("Field.Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string Field_Severity {
            get {
                return ResourceManager.GetString("Field.Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System affected.
        /// </summary>
        internal static string Field_SystemAffected {
            get {
                return ResourceManager.GetString("Field.SystemAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Field_Title {
            get {
                return ResourceManager.GetString("Field.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Filters_Apply {
            get {
                return ResourceManager.GetString("Filters.Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date range.
        /// </summary>
        internal static string Filters_DateRange {
            get {
                return ResourceManager.GetString("Filters.DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string Filters_Period {
            get {
                return ResourceManager.GetString("Filters.Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Filters_Reset {
            get {
                return ResourceManager.GetString("Filters.Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to incidents.
        /// </summary>
        internal static string IncidentCreate_Back {
            get {
                return ResourceManager.GetString("IncidentCreate.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the details below to create a new incident..
        /// </summary>
        internal static string IncidentCreate_Subtitle {
            get {
                return ResourceManager.GetString("IncidentCreate.Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a new incident.
        /// </summary>
        internal static string IncidentCreate_Title {
            get {
                return ResourceManager.GetString("IncidentCreate.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No attachments..
        /// </summary>
        internal static string IncidentDetails_Attachments_Empty {
            get {
                return ResourceManager.GetString("IncidentDetails.Attachments.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string IncidentDetails_Attachments_Title {
            get {
                return ResourceManager.GetString("IncidentDetails.Attachments.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a comment.
        /// </summary>
        internal static string IncidentDetails_Comments_AddButton {
            get {
                return ResourceManager.GetString("IncidentDetails.Comments.AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comments yet..
        /// </summary>
        internal static string IncidentDetails_Comments_Empty {
            get {
                return ResourceManager.GetString("IncidentDetails.Comments.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string IncidentDetails_Comments_Title {
            get {
                return ResourceManager.GetString("IncidentDetails.Comments.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string IncidentDetails_Download {
            get {
                return ResourceManager.GetString("IncidentDetails.Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string IncidentDetails_Field_Description {
            get {
                return ResourceManager.GetString("IncidentDetails.Field.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporter.
        /// </summary>
        internal static string IncidentDetails_Field_Reporter {
            get {
                return ResourceManager.GetString("IncidentDetails.Field.Reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description provided..
        /// </summary>
        internal static string IncidentDetails_NoDescription {
            get {
                return ResourceManager.GetString("IncidentDetails.NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new tab.
        /// </summary>
        internal static string IncidentDetails_OpenInNewTab {
            get {
                return ResourceManager.GetString("IncidentDetails.OpenInNewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string IncidentDetails_Section_Overview {
            get {
                return ResourceManager.GetString("IncidentDetails.Section.Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string IncidentDetails_Tab_Attachments {
            get {
                return ResourceManager.GetString("IncidentDetails.Tab.Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string IncidentDetails_Tab_Comments {
            get {
                return ResourceManager.GetString("IncidentDetails.Tab.Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string IncidentDetails_Tab_Details {
            get {
                return ResourceManager.GetString("IncidentDetails.Tab.Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string IncidentDetails_Tab_History {
            get {
                return ResourceManager.GetString("IncidentDetails.Tab.History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        internal static string Incidents_BackToList {
            get {
                return ResourceManager.GetString("Incidents.BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Incidents_Col_Category {
            get {
                return ResourceManager.GetString("Incidents.Col.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Incidents_Col_Date {
            get {
                return ResourceManager.GetString("Incidents.Col.Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Incidents_Col_Id {
            get {
                return ResourceManager.GetString("Incidents.Col.Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporter.
        /// </summary>
        internal static string Incidents_Col_Reporter {
            get {
                return ResourceManager.GetString("Incidents.Col.Reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string Incidents_Col_Severity {
            get {
                return ResourceManager.GetString("Incidents.Col.Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Incidents_Col_Status {
            get {
                return ResourceManager.GetString("Incidents.Col.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Incidents_Col_Title {
            get {
                return ResourceManager.GetString("Incidents.Col.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No incidents found.
        /// </summary>
        internal static string Incidents_Empty {
            get {
                return ResourceManager.GetString("Incidents.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load incidents.
        /// </summary>
        internal static string Incidents_Error_Title {
            get {
                return ResourceManager.GetString("Incidents.Error.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by ID, title, or text….
        /// </summary>
        internal static string Incidents_Search_Placeholder {
            get {
                return ResourceManager.GetString("Incidents.Search.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse and manage incident reports.
        /// </summary>
        internal static string Incidents_Subtitle {
            get {
                return ResourceManager.GetString("Incidents.Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents.
        /// </summary>
        internal static string Incidents_Title {
            get {
                return ResourceManager.GetString("Incidents.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By continuing you agree to the Terms..
        /// </summary>
        internal static string Legal_Continue {
            get {
                return ResourceManager.GetString("Legal.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Account.
        /// </summary>
        internal static string Nav_Account {
            get {
                return ResourceManager.GetString("Nav.Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Nav_Dashboard {
            get {
                return ResourceManager.GetString("Nav.Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents.
        /// </summary>
        internal static string Nav_Incidents {
            get {
                return ResourceManager.GetString("Nav.Incidents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Nav_Menu {
            get {
                return ResourceManager.GetString("Nav.Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string Nav_MyProfile {
            get {
                return ResourceManager.GetString("Nav.MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report incident.
        /// </summary>
        internal static string Nav_ReportIncident {
            get {
                return ResourceManager.GetString("Nav.ReportIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string Nav_Side {
            get {
                return ResourceManager.GetString("Nav.Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Option_Admin {
            get {
                return ResourceManager.GetString("Option.Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string Option_User {
            get {
                return ResourceManager.GetString("Option.User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string Period_Daily {
            get {
                return ResourceManager.GetString("Period.Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week {0}.
        /// </summary>
        internal static string Period_WeekLabel {
            get {
                return ResourceManager.GetString("Period.WeekLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string Period_Weekly {
            get {
                return ResourceManager.GetString("Period.Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Quick_Settings {
            get {
                return ResourceManager.GetString("Quick.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Role_Admin {
            get {
                return ResourceManager.GetString("Role.Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a role….
        /// </summary>
        internal static string Role_SelectPlaceholder {
            get {
                return ResourceManager.GetString("Role.SelectPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string Role_User {
            get {
                return ResourceManager.GetString("Role.User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are signed in..
        /// </summary>
        internal static string SignedIn_Message {
            get {
                return ResourceManager.GetString("SignedIn.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Tab_Login {
            get {
                return ResourceManager.GetString("Tab.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string Tab_Register {
            get {
                return ResourceManager.GetString("Tab.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast and simple workflow.
        /// </summary>
        internal static string Welcome_Point_Fast {
            get {
                return ResourceManager.GetString("Welcome.Point.Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern, responsive UI.
        /// </summary>
        internal static string Welcome_Point_Modern {
            get {
                return ResourceManager.GetString("Welcome.Point.Modern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure authentication &amp; roles.
        /// </summary>
        internal static string Welcome_Point_Secure {
            get {
                return ResourceManager.GetString("Welcome.Point.Secure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in or create an account to continue..
        /// </summary>
        internal static string Welcome_Subtitle {
            get {
                return ResourceManager.GetString("Welcome.Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build incidents faster. Safely..
        /// </summary>
        internal static string Welcome_Title {
            get {
                return ResourceManager.GetString("Welcome.Title", resourceCulture);
            }
        }
    }
}
