name: Build and Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5444:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      TEST_DB_CONNECTION: Host=localhost;Port=5444;Database=testdb;Username=testuser;Password=testpassword

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore IncidentReportingSystem/IncidentReportingSystem.sln

      - name: Build solution
        run: dotnet build IncidentReportingSystem/IncidentReportingSystem.sln --no-restore --configuration Release

      # Run unit tests with coverage
      - name: Run unit tests with coverage
        run: |
          dotnet test IncidentReportingSystem/IncidentReportingSystem.Tests/IncidentReportingSystem.Tests.csproj \
            --no-build \
            --configuration Release \
            --collect:"XPlat Code Coverage" \
            --results-directory IncidentReportingSystem/TestResults/Unit

      # Run integration tests with coverage
      - name: Run integration tests with coverage
        run: |
          dotnet test IncidentReportingSystem/IncidentReportingSystem.IntegrationTests/IncidentReportingSystem.IntegrationTests.csproj \
            --no-build \
            --configuration Release \
            --collect:"XPlat Code Coverage" \
            --results-directory IncidentReportingSystem/TestResults/Integration

      - name: List all coverage files
        run: ls -R IncidentReportingSystem/TestResults

      - name: Merge coverage reports and generate HTML
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.26
        with:
          reports: |
            IncidentReportingSystem/TestResults/**/coverage.cobertura.xml
          targetdir: IncidentReportingSystem/TestResults/CoverageReport
          reporttypes: Html;TextSummary
          assemblyfilters: "-xunit.*"

      - name: Upload code coverage report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: IncidentReportingSystem/TestResults/CoverageReport

      - name: Publish test results (GitHub Checks)
        uses: dorny/test-reporter@v1
        with:
          name: All Tests
          path: IncidentReportingSystem/TestResults/**/*.trx
          reporter: dotnet-trx
          fail-on-error: true
          fail-on-empty: false
