name: Build and Test

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  build:
    name: Build, Test & Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore IncidentReportingSystem/IncidentReportingSystem.sln

      - name: Build solution
        run: dotnet build IncidentReportingSystem/IncidentReportingSystem.sln --no-restore --configuration Release

      - name: Run tests with coverage
        run: dotnet test IncidentReportingSystem/IncidentReportingSystem.sln --no-build --configuration Release --collect:"XPlat Code Coverage"

      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/TestResults/*.trx'

      - name: Publish code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: '**/TestResults/**/coverage.cobertura.xml'

      - name: Publish API artifact
        run: |
          dotnet publish IncidentReportingSystem/IncidentReportingSystem.API/IncidentReportingSystem.API.csproj -c Release -o publish

      - name: Upload published artifact
        uses: actions/upload-artifact@v4
        with:
          name: incident-api
          path: publish
