name: Deploy IncidentReportingSystem (.NET 8) to Azure Web App

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  RESOURCE_GROUP: "incident-rg"
  WEBAPP_NAME: "incident-api"
  PROJECT_PATH: "IncidentReportingSystem/IncidentReportingSystem.API/IncidentReportingSystem.API.csproj"
  BASE_URL: "https://incident-api.azurewebsites.net"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      - name: Build
        run: dotnet build "${{ env.PROJECT_PATH }}" --configuration Release --no-restore

      - name: Publish
        run: dotnet publish "${{ env.PROJECT_PATH }}" --configuration Release --output ./publish --no-build

      - name: Zip artifact
        run: |
          cd publish
          zip -r ../app.zip .
          cd ..

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy ZIP to Web App
        run: |
          az webapp deploy \
            --resource-group "${{ env.RESOURCE_GROUP }}" \
            --name "${{ env.WEBAPP_NAME }}" \
            --type zip \
            --src-path "app.zip"

      - name: Enable application logs
        run: |
          az webapp log config \
            -g "${{ env.RESOURCE_GROUP }}" -n "${{ env.WEBAPP_NAME }}" \
            --application-logging filesystem --level information

      - name: Turn ON EF__ApplyMigrations and restart
        run: |
          set -e
          az webapp config appsettings set -g "${{ env.RESOURCE_GROUP }}" -n "${{ env.WEBAPP_NAME }}" --settings EF__ApplyMigrations=true
          az webapp restart -g "${{ env.RESOURCE_GROUP }}" -n "${{ env.WEBAPP_NAME }}"

      - name: Wait for /health 200 (max 120s, backoff)
        run: |
          set -e
          URL="${{ env.BASE_URL }}/health"
          DEADLINE=$(( $(date +%s) + 120 ))
          SLEEP=2
          while true; do
            CODE=$(curl -s -o /dev/null -w "%{http_code}" "$URL" || true)
            if [ "$CODE" = "200" ]; then
              echo "Health OK"
              break
            fi
            if [ $(date +%s) -ge $DEADLINE ]; then
              echo "Health failed: last HTTP $CODE"
              exit 1
            fi
            echo "Health not ready (HTTP $CODE), retrying in ${SLEEP}s..."
            sleep $SLEEP
            if [ $SLEEP -lt 10 ]; then SLEEP=$((SLEEP+2)); fi
          done

      - name: DB smoke (GET IncidentReports must be 200)
        run: |
          set -e
          TOKEN=$(curl -s "${{ env.BASE_URL }}/api/v1/Auth/token?userId=ci-smoke&role=Reader")
          CODE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $TOKEN" "${{ env.BASE_URL }}/api/v1/IncidentReports?skip=0&take=1" || true)
          if [ "$CODE" != "200" ]; then
            echo "DB smoke failed. HTTP $CODE"
            exit 1
          fi
          echo "DB smoke OK"

      - name: Turn OFF EF__ApplyMigrations and restart
        if: always()
        run: |
          az webapp config appsettings delete -g "${{ env.RESOURCE_GROUP }}" -n "${{ env.WEBAPP_NAME }}" --setting-names EF__ApplyMigrations || true
          az webapp restart -g "${{ env.RESOURCE_GROUP }}" -n "${{ env.WEBAPP_NAME }}"

      - name: Final /health check (max 120s, backoff)
        if: always()
        run: |
          URL="${{ env.BASE_URL }}/health"
          DEADLINE=$(( $(date +%s) + 120 ))
          SLEEP=2
          while true; do
            CODE=$(curl -s -o /dev/null -w "%{http_code}" "$URL" || true)
            if [ "$CODE" = "200" ]; then
              echo "Health OK after cleanup"
              break
            fi
            if [ $(date +%s) -ge $DEADLINE ]; then
              echo "Final health failed: last HTTP $CODE"
              exit 1
            fi
            echo "Waiting (HTTP $CODE)..."
            sleep $SLEEP
            if [ $SLEEP -lt 10 ]; then SLEEP=$((SLEEP+2)); fi
          done

      - name: Dump last logs on failure
        if: failure()
        run: |
          timeout 60 az webapp log tail -g "${{ env.RESOURCE_GROUP }}" -n "${{ env.WEBAPP_NAME }}" | tail -n 200 || true
