name: Render Mermaid diagrams

on:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install mermaid-cli
        run: |
          npm i -g @mermaid-js/mermaid-cli@10 puppeteer

      - name: Create Puppeteer config (no-sandbox)
        run: |
          cat > puppeteer-config.json << 'JSON'
          {
            "args": ["--no-sandbox", "--disable-setuid-sandbox"]
          }
          JSON
          cat puppeteer-config.json

      - name: Render diagrams to PNG and SVG
        run: |
          mmdc -p puppeteer-config.json -i docs/diagrams/azure-architecture.mmd -o docs/diagrams/azure-architecture.png -b transparent
          mmdc -p puppeteer-config.json -i docs/diagrams/azure-architecture.mmd -o docs/diagrams/azure-architecture.svg -b transparent
          mmdc -p puppeteer-config.json -i docs/diagrams/cicd-flow.mmd -o docs/diagrams/cicd-flow.png -b transparent
          mmdc -p puppeteer-config.json -i docs/diagrams/cicd-flow.mmd -o docs/diagrams/cicd-flow.svg -b transparent

      - name: Commit rendered images
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/diagrams/*.png docs/diagrams/*.svg || true
          if git diff --cached --quiet; then
            echo "No diagram changes to commit."
          else
            git commit -m "docs(diagrams): render Mermaid diagrams (no-sandbox)"
            git push
          fi
