name: UI CI

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: UI

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore IncidentReportingSystem/IncidentReportingSystem.UI/IncidentReportingSystem.UI.csproj

      - name: Build
        run: dotnet build IncidentReportingSystem/IncidentReportingSystem.UI/IncidentReportingSystem.UI.csproj -c Release --no-restore

      - name: Test (bUnit/xUnit)
        run: dotnet test IncidentReportingSystem/IncidentReportingSystem.UI.Tests/IncidentReportingSystem.UI.Tests.csproj -c Release --no-build
